### PR TITLE
issue #4692 liquidfun sample

### PR DESCRIPTION
**Pull request by boyu0**
fix android setting
change liquidfun submodule location.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks.

Why the liquidfun submodule was moved from `libs/liquidfun` to `libs/liquidfun/liquidfun` ?

Since liquidfun already has a `liquidfun/liquidfun` structure, now we have 3 `liquidfun` subdirectories.

eg, the Box2d code is in: `cocos2d-x-samples/libs/liquidfun/liquidfun/liquidfun`

**Comment by ricardoquesada** [comment]
Also, what are the steps to compile it for Android. I did the following:

```
$ cd ~/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android
$ ./build_native.py
```

But I got this error:

```
The Selected NDK toolchain version was 4.8 !
Android NDK: /Users/riq/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android/../../../libs/cocos2d-x/cocos/audio/android/Android.mk: Cannot find module with tag 'liquidfun' in import path
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Android NDK: The following directories were searched:
Android NDK:
make: Entering directory `/Users/riq/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android'
jni/Android.mk:27: *** Android NDK: Aborting.    .  Stop.
make: Leaving directory `/Users/riq/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android'
Traceback (most recent call last):
  File "./build_native.py", line 166, in <module>
    build(opts.ndk_build_param,opts.android_platform,opts.build_mode)
  File "./build_native.py", line 153, in build
    do_build(cocos_root, ndk_root, app_android_root,ndk_build_param,sdk_root,android_platform,build_mode)
  File "./build_native.py", line 89, in do_build
    raise Exception("Build dynamic library for project [ " + app_android_root + " ] fails!")
Exception: Build dynamic library for project [ /Users/riq/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android ] fails!
```

Any idea? Thanks.

**Comment by boyu0** [comment]
1. Because we need add our own config file in it(cmakelist.txt and android.mk), so we need to create a folder above the liquidfun submodule.
2. My libcocos2d is already compiled when I test this script, so I didn't face these errors, maybe I did something wrong, I will fix it.

**Comment by ricardoquesada** [comment]
ok. thanks.

**Comment by boyu0** [comment]
I tested it in my mac, it's ok.
I think maybe it's the submodule problem.
In my computer, the structure of the liquildfun is:

```
libs --> cocos2d-x --> ...
     |-> liquidfun --> CMakeList.txt
                   |->  Android.mk
                   |->  liquidfun   (submodule)
```

can you check that?
Thanks.

**Comment by ricardoquesada** [comment]
It is compiling now.
Apparently my submodules weren't updated. sorry about that.

**Comment by ricardoquesada** [comment]
Thanks.
So, I can run on my Nexus 7 the `Liquidfun - Testbed` without problems.
But I can't run the EyeCandy one.  This is the output:

```
04-28 10:48:09.622: D/Cocos2dxActivity(16748): model=Nexus 7
04-28 10:48:09.622: D/Cocos2dxActivity(16748): product=razor
04-28 10:48:09.622: D/Cocos2dxActivity(16748): isEmulator=false
04-28 10:48:09.632: D/dalvikvm(16748): Trying to load lib /data/app-lib/org.cocos2dx.hellocpp-2/libliquidfun_eyecandy.so 0x41e36a60
04-28 10:48:09.642: D/dalvikvm(16748): Added shared lib /data/app-lib/org.cocos2dx.hellocpp-2/libliquidfun_eyecandy.so 0x41e36a60
04-28 10:48:09.642: D/JniHelper(16748): JniHelper::setJavaVM(0x414a1f00), pthread_self() = 1074139476
04-28 10:48:09.662: E/cocos2d-x assert(16748): /Users/riq/progs/cocos2d-x-samples/samples/LiquidFun-EyeCandy/proj.android/../../../libs/cocos2d-x/cocos/2d/platform/android/CCApplication.cpp function:getInstance line:79
04-28 10:48:09.662: A/libc(16748): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 16768 (Thread-5743)
04-28 10:51:20.858: I/dalvikvm(17564): Enabling JNI app bug workarounds for target SDK version 9...
04-28 10:51:20.898: D/Cocos2dxActivity(17564): model=Nexus 7
04-28 10:51:20.908: D/Cocos2dxActivity(17564): product=razor
04-28 10:51:20.908: D/Cocos2dxActivity(17564): isEmulator=false
04-28 10:51:20.918: D/dalvikvm(17564): Trying to load lib /data/app-lib/org.cocos2dx.hellocpp-1/libliquidfun_eyecandy.so 0x41e30eb0
04-28 10:51:20.918: D/dalvikvm(17564): Added shared lib /data/app-lib/org.cocos2dx.hellocpp-1/libliquidfun_eyecandy.so 0x41e30eb0
04-28 10:51:20.918: D/JniHelper(17564): JniHelper::setJavaVM(0x414a1f00), pthread_self() = 1074139476
04-28 10:51:20.968: I/Adreno-EGL(17564): <qeglDrvAPI_eglInitialize:320>: EGL 1.4 QUALCOMM Build: I0404c4692afb8623f95c43aeb6d5e13ed4b30ddbDate: 11/06/13
04-28 10:51:21.008: D/cocos2d-x debug info(17564): {
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_vertex_array_object: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_BGRA8888: false
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_ATITC: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_S3TC: false
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  cocos2d.x.version: cocos2d-x 3.0
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_discard_framebuffer: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  cocos2d.x.compiled_with_profiler: false
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_PVRTC: false
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  cocos2d.x.build_type: DEBUG
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.renderer: Adreno (TM) 320
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_ETC1: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  cocos2d.x.compiled_with_gl_state_cache: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.version: OpenGL ES 3.0 V@53.0 AU@  (CL@)
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.supports_NPOT: true
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.max_texture_units: 32
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.vendor: Qualcomm
04-28 10:51:21.008: D/cocos2d-x debug info(17564):  gl.max_texture_size: 4096
04-28 10:51:21.008: D/cocos2d-x debug info(17564): }
04-28 10:51:21.198: D/main(17564): cocos_android_app_init
04-28 10:51:21.228: E/libEGL(17564): called unimplemented OpenGL ES API
04-28 10:51:21.228: A/libc(17564): Fatal signal 11 (SIGSEGV) at 0x0c7db493 (code=1), thread 17577 (Thread-5790)
```

Any idea?thanks.

**Comment by boyu0** [comment]
It's ok on sumsung i9000
I will check that.

**Comment by ricardoquesada** [comment]
Ok. thanks.
One more thing: could you change then names of the game? I don't know how to do that on Andriod projects.

Both projects appear as "LiquidFun" on my Android device but their names should be "LiquidFun - Testbed" and "LiquidFun - EyeCandy".

Thanks!

**Comment by boyu0** [comment]
No problem, I will fix this.

**Pull request merged**
