### PR TITLE
issue #4692: add condition to update the VBO buffer.

### PR DESCRIPTION
**Pull request by boyu0**
1. add condition to update the VBO buffer.
2. fix android app name.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Hi boyu0,
What bug did you find with the VBO code?

It looks fine to me. Was it crashing for you? What are the steps to reproduce it?
In your code you are checking whether VAOs are enabled, but my code is not using VAO at all.

thanks.

**Comment by boyu0** [comment]
@ricardoquesada 
You said that EyeCandy crashed at your Nexus 7, I discussed with @LinWenhai, he think you phone doesn't support `glUnmapBuffer`, and I checked codes in our engine, we use `glMapBuffer` and `glUnmapBuffer` only when devices support VAO, so I think maybe `glUnmapBuffer` only be supported in opengl es3.0, or maybe has some problem in es2.0, so I moved this 2 api under the VAO support condition checking.

**Comment by ricardoquesada** [comment]
@boyu0 
Interesting theory. Thanks.
I'll try it today.

**Comment by ricardoquesada** [comment]
thanks. it works as expected with your patch.

**Pull request merged**
